version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es_network
    volumes:
      - es_data:/usr/share/elasticsearch/data
    
  postgres:
    image: 'postgres:17'
    container_name: postgres_fw_main
    environment:
      POSTGRES_DB: 'foxwatch'
      POSTGRES_USER: 'foxwatch'
      POSTGRES_PASSWORD: 'foxwatch'
      POSTGRES_PORT: 5432
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    networks:
      - postgres

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - es_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  es_network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
